### ISSUE TITLE
Can not get it to work on Vim 9.1

### ISSUE THREAD

**Issue by baco** [xiyaowong/coc-symbol-line#14]
I've installed it via `:CocInstall coc-symbol-line`.  After that, the extension appears listed on `:CocList extensions` but as loaded (`+`), not as enabled (`*`).  Nothing happens in Vim at all when opening a file.

I get the following error with `:CocOpenLog`:
```
2024-08-05T21:38:59.178 INFO (pid:83310) [plugin] - coc.nvim initialized with node: v21.6.0 after [33m577[39m
2024-08-05T21:38:59.185 ERROR (pid:83310) [node-client] - request error on "nvim_command" [ [32m'runtime plugin/coc_symbol_line.vim'[39m ] Error: request error on "nvim_command" - Vim(highlight):E254: Cannot allocate color 0 on api "command" ["runtime plugin/coc_symbol_line.vim"]
    at Object.activate (/home/baco/.config/coc/extensions/node_modules/[4mcoc-symbol-line[24m/lib/index.js:5673:14)
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
    at async /home/baco/src/dotfiles/vim/pack/lsp/start/coc.nvim/build/index.js:78892:27
2024-08-05T21:38:59.186 ERROR (pid:83310) [extensions-manager] - Error on active extension coc-symbol-line: Error: request error on "nvim_command" - Vim(highlight):E254: Cannot allocate color 0 on api "command" ["runtime plugin/coc_symbol_line.vim"]
    at Object.activate (/home/baco/.config/coc/extensions/node_modules/[4mcoc-symbol-line[24m/lib/index.js:5673:14)
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
    at async /home/baco/src/dotfiles/vim/pack/lsp/start/coc.nvim/build/index.js:78892:27
2024-08-05T21:38:59.187 ERROR (pid:83310) [server] - unhandledRejection  Promise {
  [36m<rejected>[39m Error: request error on "nvim_command" - Vim(highlight):E254: Cannot allocate color 0 on api "command" ["runtime plugin/coc_symbol_line.vim"]
      at Object.activate (/home/baco/.config/coc/extensions/node_modules/[4mcoc-symbol-line[24m/lib/index.js:5673:14)
  [90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
      at async /home/baco/src/dotfiles/vim/pack/lsp/start/coc.nvim/build/index.js:78892:27
} Error: request error on "nvim_command" - Vim(highlight):E254: Cannot allocate color 0 on api "command" ["runtime plugin/coc_symbol_line.vim"]
    at Object.activate (/home/baco/.config/coc/extensions/node_modules/[4mcoc-symbol-line[24m/lib/index.js:5673:14)
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
    at async /home/baco/src/dotfiles/vim/pack/lsp/start/coc.nvim/build/index.js:78892:27
2024-08-05T21:39:03.505 INFO (pid:83310) [attach] - receive notification: openLog []
2024-08-05T21:39:04.168 ERROR (pid:83310) [timing] - activate coc-symbol-line timeout after 5000ms
```

Is the CoC extension working for the _non-Neo_ Vim editor?

**Comment by xiyaowong** [comment]
It should support vim. I'll fix it when I have time.

**Comment by baco** [comment]
I can provide the following log from CoC's `node` running Node client in debug mode:

[coc.log](https://github.com/user-attachments/files/16504176/coc.log)
